# Generated by Django 3.0 on 2020-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectowner', models.CharField(default='Codethug', max_length=30)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
