# Generated by Django 3.0 on 2020-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectowner',
            field=models.CharField(max_length=30),
        ),
    ]
